namespace Woof.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public class User
    {
        public int UserID { get; set; } // Automatically generated by the database

        [Required]
        public string Username { get; set; }

        [Required]
        [EmailAddress]
        [MaxLength(256)]
        public string Email { get; set; } // Unique constraint added here

        [Required]
        public string Password { get; set; }

        public DateTime RegistrationDate { get; set; } // Set this when a new user is created

        public User()
        {
            RegistrationDate = DateTime.Now;
        }
        public int? OwnedDogs { get; set; }
        public int? KennelID { get; set; } // Links with the Kennels table, can be null
        public int RoleID { get; set; } // Links with the Roles table
    }

}
